### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by foux** [CircleCI-Public/helm-orb#15]
## What would you like to be added

Helm 3 is now out of beta and the latest stable release. The current version of this orb works only with Helm 2 (especially with the init command)

## Why is this needed

Helm 3 is now the standard version and Helm 2 will be less and less used

**Comment by lokst** [comment]
@foux Thank you for your feedback, we'll look into this!

**Comment by lokst** [comment]
@foux Could you try version 0.2.2 of the orb? It skips `helm init` if the version of `helm` installed is not 2.

**Comment by foux** [comment]
Hi @lokst!
It works for the install, thanks a lot. There's another issue, but that seems more linked with Helm (https://github.com/helm/helm/issues/7020)
Except if you have any idea on this one ;). To sum up, on certain CircleCI machine (but not all the time...), helm3 will just exit with a return code of 1

**Comment by lokst** [comment]
@foux Thanks for the report, I'll try reproducing the error!

**Comment by lokst** [comment]
@foux I wasn't able to reproduce the issue, would you like to take a look at my config as a reference and see if it helps?

```
version: 2.1

orbs:
  helm: circleci/helm@0.2.2

jobs:
  build-machine:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.0.0
      - run:
          name: Test
          command: |
            helm version
  build-docker:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.0.0
      - run:
          name: Test
          command: |
            helm version
workflows:
  test:
    jobs:
      - build-machine
      - build-docker
```
