### ISSUE TITLE
"Error: no repositories found. You must add one before updating" error when using helm 3

### ISSUE THREAD

**Issue by edalford11** [CircleCI-Public/helm-orb#18]
### What happened

With the job defined as

```yaml
jobs:
  deploy:
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: test-eks-cluster
          aws-region: "${AWS_REGION}"
      - helm/install-helm-client:
          version: v3.1.2
      - helm/upgrade-helm-chart:
          chart: kubernetes/helm_chart_name
          release-name: helm_chart_name
```

Results in the error on the helm/upgrade-helm-chart step:
```
helm repo update
Error: no repositories found. You must add one before updating
```

### Expected behavior

Shouldn't error out

Current work around is adding this step just before the helm/upgrade-helm-chart step:
```yaml
- run:
    name: "Add helm repo"
    command: |
      helm repo add stable https://kubernetes-charts.storage.googleapis.com
```
