### ISSUE TITLE
How to Use with aws-cli or how to specify cluster?

### ISSUE THREAD

**Issue by phil-lgr** [CircleCI-Public/helm-orb#4]
Hi, I'm trying to use: 

```
orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-ecr: circleci/aws-ecr@4.0.1
  helm: circleci/helm@0.1.0
```

unfortunately the `circleci/aws-cli` doesn't have `aws eks` for some reason.. so how does one use this helm orb? are we suppose to setup the kube config before?

Thanks,

Phil
