### ISSUE TITLE
Make values-to-override a list or map, to make it easier to specify multiple values

### ISSUE THREAD

**Issue by AlanRaisonNews** [CircleCI-Public/helm-orb#41]
## What would you like to be added

CircleCI config files can be awkward to edit if there are even a few override values to specify. If the parameter was an array or perhaps a map, it would be easier to format these values.

## Why is this needed

This would make working with overridden values much easier, from a readability point of view.

**Comment by BDBI-Duncan** [comment]
This would be a welcome addition to the orb. Any word on if this is on the horizon?

**Comment by brivu** [comment]
Hey @AlanRaisonNews and @BDBI-Duncan, 

Thanks for your input here.  Would either of you be able to give me an example?  Specifically how a config looks now versus what you'd like to see?  

Let me know and I can investigate this further.  

Thanks! 
-Brian

**Comment by AlanRaisonNews** [comment]
So for example, instead of the current:
```yaml
      - helm/upgrade-helm-chart:
          atomic: true
          timeout: 10m
          helm-version: v3.7.0
          chart: ./helm
          namespace: << parameters.namespace >>
          release-name: << parameters.release-name >>
          values: << parameters.values >>
          values-to-override: circle_build_num=<< pipeline.number >>,parameter_1=<< parameters.parameter_1 >>,parameter_2=value_2,...
```

you could have:
```yaml
      - helm/upgrade-helm-chart:
          atomic: true
          timeout: 10m
          helm-version: v3.7.0
          chart: ./helm
          namespace: << parameters.namespace >>
          release-name: << parameters.release-name >>
          values: << parameters.values >>
          values-to-override:
            circle_build_num: << pipeline.number >>
            parameter_1: <<parameters.parameter_1>>
            parameter_2: value_2
```

or equivalently as a list.

It is particularly tricky at the moment as spaces are not allowed between the comma and the next parameter name.
