### ISSUE TITLE
Allow to add external repositories

### ISSUE THREAD

**Issue by arvid-m** [CircleCI-Public/helm-orb#46]
## What would you like to be added

Possibility to add an external repository. Something like:

```yaml

jobs:
  install-helm-chart:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: Cluster name
        type: string
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - helm/add-helm-repository: # Just a suggestion
          name: grafana
          url: https://grafana.github.io/helm-charts
      - helm/install-helm-chart:
          chart: grafana/grafana
          helm-version: v3.2.4
          release-name: grafana-release
orbs:
  aws-eks: circleci/aws-eks@0.2
  helm: circleci/helm@1.0
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: test-cluster
      - install-helm-chart:
          cluster-name: test-cluster
          requires:
            - aws-eks/create-cluster
```

## Why is this needed

Since the stable repo is far beyond deprecation, it would be great with a command that could add and update a repository.

I'd be happy help out if this is something that should be implemented. 🙂
