### ISSUE TITLE
Ability to pass multiple values files as an array

### ISSUE THREAD

**Issue by gavinclarkeuk** [CircleCI-Public/helm-orb#47]
## What would you like to be added

Similarly to https://github.com/CircleCI-Public/helm-orb/issues/41 it would be useful to be able pass multiple values files to the orb as an array:

 ```
     - helm/upgrade-helm-chart:
          atomic: true
          timeout: 10m
          helm-version: v3.7.0
          chart: ./helm
          namespace: << parameters.namespace >>
          release-name: << parameters.release-name >>
          values:
            - values-common.yaml
            - values-<<parameters.environment>>.yaml
```

## Why is this needed

This would enable more flexible value files configuration, enabling deduplication amongst other things.
