### ISSUE TITLE
Can't set the values parameter as a simple string

### ISSUE THREAD

**Issue by rubensa** [CircleCI-Public/helm-orb#58]
Since the change:
https://github.com/CircleCI-Public/helm-orb/commit/d6dfabc762c6ae4696ec8d89740b200668a7d3a0

that sets this:
https://github.com/CircleCI-Public/helm-orb/blob/d6dfabc762c6ae4696ec8d89740b200668a7d3a0/src/scripts/upgrade-helm-chart.sh#L32

You can't use something like:
```
    steps:
      - helm/upgrade-helm-chart:
          add-repo: "https://charts.bitnami.com/bitnami"
          chart: charts/my-chart
          release-name: app
          values: "my-custom-values.yaml"
```
you get an error like:
`my-custom-values.yaml: Permission denied`

You are forced to do a "trick" like:
```
    environment:
      HELM_CHART_VALUES: "my-custom-values.yaml"
    steps:
      - helm/upgrade-helm-chart:
          add-repo: "https://charts.bitnami.com/bitnami"
          chart: charts/my-chart
          release-name: app
          values: "echo 'my-custom-values.yaml'"
```

**NOTE**:  This is caused by the **eval** usage
